# Generated by Django 4.2.7 on 2024-02-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.CharField(blank=True, max_length=50)),
                ('profit', models.IntegerField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
